module.exports = {
  COLLECTOR: "COLLECTOR",
  UPGRADER: "UPGRADER",
  BIG_UPGRADER: "BIG_UPGRADER",
  BIG_COLLECTOR: "BIG_COLLECTOR",
  BUILDER: "BUILDER",
  ATTACKER: "ATTACKER",
  REPAIRER: "REPAIRER",
  TOWER_FILLER: "TOWER_FILLER"
}
